core/urls.py
from django.urls import path

from core import views
app_names = "core"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("",views.index, name="feed"),

    # Ajax path
    path("create-post/", views.create_post, name="create-post"),
    path("like-post/", views.like_post, name="like-post"),
    path("comment-post/", views.comment_on_post, name="comment-post"),
]

facebook_prj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(("core.urls",'core'),namespace='core')),
    path("user/",include(("userauths.urls",'userauths'),namespace='userauths')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path("sign-up/",views.RegisterView, name="sign-up"),
    path("sign-in/",views.LoginView, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from shortuuid.django_fields import ShortUUIDField
from django.db.models.signals import post_save
from django.utils.text import slugify
import shortuuid
# Create your models here.

GENDER = (
    ("male","Male"),
    ("female","Female"),
    ("others","Others")
)

RELATIONSHIP = (
    ("single","Single"),
    ("in a relationship","In a RelationShip"),
    ("it is complex","It's Complex")
)

def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s"%(instance.user.id,ext),
    return 'user_{0}/{1}'.format(instance.user.id,filename)

class User(AbstractUser):
    full_name = models.CharField(max_length=200)
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    gender = models.CharField( max_length=50, choices=GENDER, default="male")

    otp = models.CharField( max_length=10,null=True,blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Profile(models.Model):
    pid = ShortUUIDField(length = 7, max_length = 25, alphabet = 'abcdefghijklmnopqrstuvwxyz')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = models.ImageField(upload_to=user_directory_path,blank=True,default="cover.jpg")
    image = models.ImageField(upload_to=user_directory_path,blank=True,default="default.jpg")
    full_name = models.CharField(max_length=200,null=True,blank=True)
    phone = models.CharField(max_length=20,null=True,blank=True)
    gender = models.CharField( max_length=50, choices=GENDER, default="male")
    relationship = models.CharField( max_length=50, choices=RELATIONSHIP, default="single")
    bio = models.CharField( max_length=500,null=True,blank=True)
    about_me = models.TextField( max_length=500,null=True,blank=True)
    city = models.CharField( max_length=500,null=True,blank=True)
    country = models.CharField( max_length=500,null=True,blank=True)
    state = models.CharField( max_length=500,null=True,blank=True)
    address = models.CharField( max_length=500,null=True,blank=True)
    working_at = models.CharField( max_length=500,null=True,blank=True)
    instagram = models.CharField( max_length=500,null=True,blank=True)
    whatsapp = models.CharField( max_length=500,null=True,blank=True)
    verified = models.BooleanField(default=False)
    followers = models.ManyToManyField(User, blank=True, related_name="followers")
    following = models.ManyToManyField(User, blank=True, related_name="following")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    blocked = models.ManyToManyField(User, blank=True, related_name="blocked")
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True,blank=True, null=True)

    def __str__(self):
        if (self.full_name == "" or self.full_name == None):
            return "%s the user" % self.user.username
        else:
            return self.full_name

    def save(self,*args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:2]
            self.slug = slugify(self.full_name)+ '-' + str(uniqueid.lower())
        super(Profile, self).save(*args, **kwargs)

def create_user_profile(sender, instance, created,  **kwargs):
    if created:
        Profile.objects.create(user= instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ImageField, FileInput, TextInput, Select

from userauths.models import Profile, User

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Full Name'}), max_length=100, required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Username'}), max_length=100, required=True)
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Mobile No.'}), max_length=20, required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': '' , 'id': "", 'placeholder':'Email Address'}), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id': "", 'placeholder':'Password'}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id': "", 'placeholder':'Confirm Password'}), required=True)


    class Meta:
        model = User
        fields = ['full_name','username','email','phone','gender','password1','password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class']="with-border"

userauths/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse
from userauths.forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from userauths.models import Profile, User
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@csrf_exempt
def RegisterView(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are registered!")
        return redirect(reverse('core:feed'))

    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data.get("full_name")
        phone = form.cleaned_data.get("phone")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        full_name = form.cleaned_data.get("full_name")
        full_name = form.cleaned_data.get("full_name")

        user = authenticate(email=email, password=password)
        login(request, user)


        profile = Profile.objects.get(user= request.user)
        profile.full_name= full_name
        profile.phone= phone
        profile.save()

        messages.success(request, f"hi {full_name}. your account created successfully")
        return redirect(reverse('core:feed'))
    
    context = {
        "form" : form
    }
    return render(request,'userauths/sign-up.html',context)

@csrf_exempt
def LoginView(request):
    # if request.user.is_authenticated:
    #     return redirect('core:feed')
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)

            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are Logged In")
                return redirect('core:feed')
            else:
                messages.error(request, 'Username or password does not exit.')
                return redirect(reverse("userauths:sign-up"))
        
        except:
            messages.error(request, 'User does not exist')
            return redirect(reverse("userauths:sign-up"))
        

    return HttpResponseRedirect("/")

def LogoutView(request):
    logout(request)
    messages.success(request, 'You have been logged out')
    return redirect("userauths:sign-up")

templates/userauths/sign-up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="assets/images/favicon.png" rel="icon" type="image/png">

    <!-- Basic Page Needs
        ================================================== -->
    <title>Socialite Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Socialite is - Professional A unique and beautiful collection of UI elements">

    <!-- icons
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">

    <!-- CSS 
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #f0f2f5;
        }
    </style>

</head>

<body>


    <div class="lg:flex max-w-5xl min-h-screen mx-auto p-6 py-10">
        <div class="flex flex-col items-center lg: lg:flex-row lg:space-x-10">

            <div class="lg:mb-12 flex-1 lg:text-left text-center">
                <img src="{% static 'assets/images/logo.png' %}" alt="" class="lg:mx-0 lg:w-52 mx-auto w-40">
                <p class="font-medium lg:mx-0 md:text-2xl mt-6 mx-auto sm:w-3/4 text-xl"> Connect with friends and the world around you on Socialite.</p>
            </div>
            <div class="lg:mt-0 lg:w-96 md:w-1/2 sm:w-2/3 mt-10 w-full">
                {% if form.errors %}
                <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                    <strong class="font-bold">{{form.errors}}</strong>
                    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                      <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
                    </span>
                  </div> 
                {% endif %}
                {% if messages %}
                    {% for message in messages %}
                            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                                <strong class="font-bold">{{message}}</strong>
                                <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                                <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
                                </span>
                            </div> 
                    {% endfor %}
                {% endif %}
                <form class="p-6 space-y-4 relative bg-white shadow-lg rounded-lg" method="post" action="{%url 'userauths:sign-in'%}">
                    <input type="email" name="email" placeholder="Email or Phone Number" class="with-border">
                    <input type="password" name="password" placeholder="Password" class="with-border">
                    <button type="submit" class="bg-blue-600 font-semibold p-3 rounded-md text-center text-white w-full">
                        Log In
                    </button>
                    <a href="#" class="text-blue-500 text-center block"> Forgot Password? </a>
                    <hr class="pb-3.5">
                    <div class="flex">
                        <a href="#register" type="button" class="bg-green-600 hover:bg-green-500 hover:text-white font-semibold py-3 px-5 rounded-md text-center text-white mx-auto" uk-toggle>
                            Create New Account
                        </a>
                    </div>
                </form>

                <div class="mt-8 text-center text-sm"> <a href="#" class="font-semibold hover:underline"> Create a Page </a> for a celebrity, band or business </div>
            </div>

        </div>
    </div>

    <!-- This is the modal -->
    <div id="register" uk-modal>
        <div class="uk-modal-dialog uk-modal-body rounded-xl shadow-2xl p-0 lg:w-5/12">
            <button class="uk-modal-close-default p-3 bg-gray-100 rounded-full m-3" type="button" uk-close></button>
            <div class="border-b px-7 py-5">
                <div class="lg:text-2xl text-xl font-semibold mb-1"> Sign Up</div>
                <div class="text-base text-gray-600"> It’s quick and easy.</div>
            </div>
            <form class="p-7 space-y-5" method="post">
                {% csrf_token %}
                <div class="grid lg:grid-cols-2 gap-5">
                    {{form.full_name}}
                    {{form.username}}
                </div>
                {{form.email}}
                {{form.password1}}
                {{form.password2}}

                <div class="grid lg:grid-cols-2 gap-3">
                    <div>
                        <label class="mb-2"> Gender </label>
                        {{form.gender}}

                    </div>
                    <div>
                        <label class="mb-2"> Phone: optional  </label>
                        {{form.phone}}
                    </div>
                </div>
                <p class="text-xs text-gray-400 pt-3">By clicking Sign Up, you agree to our
                    <a href="#" class="text-blue-500">Terms</a>,
                    <a href="#">Data Policy</a> and
                    <a href="#">Cookies Policy</a>. You may receive SMS Notifications from us and can opt out any time.
                </p>
                <div class="flex">
                    <button type="submit" class="bg-blue-600 font-semibold mx-auto px-10 py-3 rounded-md text-center text-white">
                        Get Started
                    </button>
                </div>
            </form>

        </div>
    </div>

    <!-- For Night mode -->
    <script>
        (function(window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);

        (function(window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function(event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>

    <!-- Javascript
    ================================================== -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>

</body>

</html>